#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Frontend formatting
echo "🔍 Formatting frontend code..."
cd frontend && npm run format

# Backend formatting
echo "🔍 Formatting backend code..."
cd ../backend && npm run format

cd ..
echo "✅ Formatting complete. Proceeding with commit."